# Stage 1: build
FROM node:16.15.0-alpine3.15 as builder
WORKDIR /home/app
COPY . .

RUN npm ci && npm cache clean --force
RUN npm run build

# Stage 2: deploy and serve
FROM nginx:1.21.6-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]