@jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcnlwdGljIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTUzMjQyNzd9.v9c9vxIvzzQiMwmqq4GwpfUjQiJfdVdH-7YS4E6dMbs
@url=http://localhost:8080


### auth requests

POST {{url}}/api/authenticate HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}

###

POST {{url}}/api/create_account HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "user69",
    "password": "420"
}


### message requests

GET {{url}}/message HTTP/1.1
Authorization: Bearer {{jwt}}


###

GET {{url}}/message/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

GET {{url}}/message/room/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

POST {{url}}/message HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}} 

{
    
    "userId": 1,
    "username": "john@smith.com",
    "roomId": 1,
    "messageContent": "http test 1"
}

###

PUT {{url}}/message/5 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}} 

{
    "messageId": 5,
    "userId": 1,
    "username": "john@smith.com",
    "roomId": 1,
    "messageContent": "http test 5",
    "timeStamp": "2022-06-15T15:59:14.887+00:00"
}

###

DELETE {{url}}/message/5 HTTP/1.1
Authorization: Bearer {{jwt}} 

### room requests

GET {{url}}/room/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

GET {{url}}/room/user/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### user requests

GET {{url}}/user/john@smith.com HTTP/1.1

###