@jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcnlwdGljIiwic3ViIjoiQmlnQmVhcjg4IiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NTU0MjQ2NzJ9.nIMMpdtsYwbqhYDKBIRHDwKmxvR3MdPUWHZYDKKfvng
@awsurl=http://cryptic-api.us-east-1.elasticbeanstalk.com

POST {{awsurl}}/api/authenticate HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "BigBear88",
    "password": "Holodeck88"
}

###

POST {{awsurl}}/api/create_account HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": " ",
    "password": " "
}


### message requests

GET {{awsurl}}/message HTTP/1.1
Authorization: Bearer {{jwt}}


###

GET {{awsurl}}/message/6 HTTP/1.1
Authorization: Bearer {{jwt}}

###

GET {{awsurl}}/message/room/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

POST {{awsurl}}/message HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}} 

{
    
    "userId": 1,
    "username": "john@smith.com",
    "roomId": 1,
    "messageContent": "http test 11"
}

###

PUT {{awsurl}}/message/6 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}} 

{
    "messageId": 6,
    "userId": 1,
    "username": "john@smith.com",
    "roomId": 1,
    "messageContent": "http test 6",
    "timeStamp": "2022-06-15T15:59:14.887+00:00"
}

###

DELETE {{awsurl}}/message/9 HTTP/1.1
Authorization: Bearer {{jwt}} 

### room requests

GET {{awsurl}}/room/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

GET {{awsurl}}/room/user/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### user requests

GET {{awsurl}}/user/BigBear88 HTTP/1.1
Authorization: Bearer {{jwt}}

###

POST {{awsurl}}/user/room/2 HTTP/1.1
