@jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcnlwdGljIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTUzMjE5NTN9.FCfnDvMZofrmjBUtmZw3Z9j4BhNkdfuc1-gpTN4jtnc
@awsurl=http://cryptic-api.us-east-1.elasticbeanstalk.com
@localurl=http://localhost:8080

### auth requests

POST {{awsurl}}/api/authenticate HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}

###

POST {{awsurl}}/api/create_account HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "user69",
    "password": "420"
}


### message requests

GET {{awsurl}}/message HTTP/1.1
Authorization: Bearer {{jwt}}


###

GET {{awsurl}}/message/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

GET {{awsurl}}/message/room/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

POST {{awsurl}}/message HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}} 

{
    
    "userId": 1,
    "username": "john@smith.com",
    "roomId": 1,
    "messageContent": "http test 1"
}

###

PUT {{awsurl}}/message/5 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}} 

{
    "messageId": 5,
    "userId": 1,
    "username": "john@smith.com",
    "roomId": 1,
    "messageContent": "http test 5",
    "timeStamp": "2022-06-15T15:59:14.887+00:00"
}

###

DELETE {{awsurl}}/message/5 HTTP/1.1
Authorization: Bearer {{jwt}} 

### room requests

GET {{awsurl}}/room/1
Authorization: Bearer {{jwt}}

###below comments are just for reference

# @url = http://localhost:8080/api/hero
# @url=http://ec2-3-139-99-81.us-east-2.compute.amazonaws.com:8080/api/hero

# GET {{url}} HTTP/1.1

# ### 

# GET {{url}}/1 HTTP/1.1

# ###

# POST {{url}} HTTP/1.1
# Content-Type: application/json
# Accept: application/json
# Authorization: Bearer {{jwt}}

# {
#     "superName": "Scarlet Witch",
#     "realName": "Wanda Maximoff",
#     "imageUrl": null,
#     "powers": [
#         { "powerId": 9, "name": "Red Magic" }
#     ]
# }

# ###

# PUT {{url}}/9 HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer {{jwt}}

# {
#     "heroId": 9,
#     "superName": "Scarlet Witch",
#     "realName": "Wanda Maximoff",
#     "imageUrl": null,
#     "powers": [
#         { "powerId": 9, "name": "Red Magic" },
#         { "powerId": 10, "name": "Telekinesis" }
#     ]
# }

# ###

# DELETE {{url}}/8 HTTP/1.1
# Authorization: Bearer {{jwt}}

# ###



###